apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-component-template
  title: Onboard your component to RHDH
  description: Create and register a new component to RHDH Catalog 
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide new component details
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          description: Human readable name for the component
          default: my-rh1-component
          maxLength: 20
        description:
          title: Description
          type: string
          description: Help others understand what this component is for.
          default: My Red Hat One component
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: {{ gitlab_host }}
              enum:
                - {{ gitlab_host }}
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: {{ gitlab_destination_group }}
              enum:
                - {{ gitlab_destination_group }}
  steps:
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: {{ "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}" }}
        catalogInfoPath: "/catalog-info.yaml"
  
  output:
    links:
      - title: Open Component in catalog
        icon: catalog
        entityRef: {{ '${{ steps.register.output.entityRef }}' }}